import type { Metadata } from "next";
import Header from "./components/ui/landing/Header";
import Footer from "./components/ui/landing/Footer";
import { SearchProvider } from "./contexts/SearchContext";
import { CartProvider } from "./contexts/CartContext";
import { AuthProvider } from "./contexts/AuthContext";
import "./globals.css";
import { Poppins } from "next/font/google";
import FixedSearchButton from "./components/ui/landing/FixedSearchButton";
import GlobalSearch from "./components/ui/landing/GlobalSearch";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.variable} font-poppins`}>
        <AuthProvider>
          <CartProvider>
            <SearchProvider>
              <Header />
              <main>{children}</main>
              <Footer />
              <FixedSearchButton />
              <GlobalSearch />
            </SearchProvider>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
