import type { Metadata } from "next";
import Header from "./components/ui/landing/Header";
import Footer from "./components/ui/landing/Footer";
import { SearchProvider } from "./contexts/SearchContext";
import { Providers } from "./providers";
import "./globals.css";
import { Poppins } from "next/font/google";
import FixedSearchButton from "./components/ui/landing/FixedSearchButton";
import GlobalSearch from "./components/ui/landing/GlobalSearch";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Shopssentials",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://js.paystack.co/v1/inline.js"></script>
      </head>
      <body className={`antialiased ${poppins.variable} font-poppins`}>
        <Providers>
          <SearchProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <FixedSearchButton />
            <GlobalSearch />
          </SearchProvider>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </Providers>
      </body>
    </html>
  );
}
